FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY unavailable.html /etc/nginx/html/unavailable.html
COPY assets/style.css /etc/nginx/html/assets/style.css
COPY assets/images/logo2.png /etc/nginx/html/assets/images/logo2.png
COPY assets/images/3c7ac384742589.5d66896467ca0.jpg /etc/nginx/html/assets/images/3c7ac384742589.5d66896467ca0.jpg